### ISSUE TITLE
"Remote Disc" uses wrong icon, changes in icons10.plist without effect

### ISSUE THREAD

**Issue by Canubiz** [w0lfschild/colorfulSidebar_9#10]
"Remote Disc" in sidebar (to access shared DVDs or CDs from another Mac in the network) uses a generic shared network volume icon instead of a CD icon.
![bildschirmfoto 2019-01-06 um 14 04 02 gmt 1](https://user-images.githubusercontent.com/11623296/50736371-1c221e80-11bd-11e9-8d3a-78d003fa6bb2.png)

Weirdly enough it's not using the CD icon referenced in icons.plist or icons10.plist (I am running Sierra here) and any changes to another icon also don't have any effect.
![bildschirmfoto 2019-01-06 um 14 08 18 gmt 1](https://user-images.githubusercontent.com/11623296/50736340-be8dd200-11bc-11e9-97b5-a82c267ec5bb.png)

**Comment by w0lfschild** [comment]
Have you tried just adding `Remote Disk` to the `/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/CDAudioVolumeIcon.icns` array?

You should be able to theme anything directly by using the name that shows in the sidebar.

My guess would be that the Finder node no longer reports as `x-applefinder-vnode:Remote%20Disc`
