### ISSUE TITLE
No function @10.11.6

### ISSUE THREAD

**Issue by taebde** [w0lfschild/colorfulSidebar_9#11]
After installing mySIMBL.app and opening the "colorfulsidebar" - i can see that she is installed but nothing else happens.
![Bildschirmfoto 2019-07-08 um 20 59 02](https://user-images.githubusercontent.com/52686670/60856186-93178e80-a1c3-11e9-82d0-02b495a3eaf5.png)
![Bildschirmfoto 2019-07-08 um 20 59 19](https://user-images.githubusercontent.com/52686670/60856190-96127f00-a1c3-11e9-8a4e-84136c1290d9.png)

I restarted the finder as well i rebooted the system. No other results.

**Comment by w0lfschild** [comment]
My guess is maybe you have System Integrity Protection on or something akin to that.

Try using [MacForge](https://github.com/w0lfschild/MacForge) instead of mySIMBL.
