### ISSUE TITLE
colorfulSidebar crashes causing infinite login loop

### ISSUE THREAD

**Issue by adamwinn** [w0lfschild/colorfulSidebar_9#12]
See the video for this behavior:  https://streamable.com/s/9k8on/kuwkpa

When colorfulSidebar is enabled, it crashes and kicks the user out to the login screen.  Upon logging back in, it crashes again and kicks them back out again.

MacForge version 0.12.4.  colorfulSidebar version 1.7.0.  

This doesn't happen with colorfulSidebar 1.6.0.

You have to reboot into Safe Mode and remove the plugin from /Library/Application Support and then you're able to login again

**Comment by w0lfschild** [comment]
Well now. That seems really serious. Do you have crash logs for `loginwindow` at `/Library/Logs/DiagnosticReports`.

**Comment by w0lfschild** [comment]
Just put out 1.7.1 which should fix the issue. Please let us know if you’re still experiencing problems after updating.

**Comment by adamwinn** [comment]
1.7.1 fixed the issue! Thanks for the quick fix!

**Comment by dardo82** [comment]
I've got the same issue with the last version on 10.13.6
