### ISSUE TITLE
plugin breaks unarchiving files

### ISSUE THREAD

**Issue by the3ye** [w0lfschild/colorfulSidebar_9#3]
macOS 10.12.6
colorfulSidebar_9 ver 1.5
When I try to extract some files using Unarchiver app instead of extracting files, application opens. Same with few other file formats. 
When using built-in Archive Utility App it doesn't kill the app once it's finished as it should.
Both options are working when using colorfulSidebar_9 ver 1.3.2

**Comment by w0lfschild** [comment]
Thanks for the heads up. Probably best to just blacklist that app in mySIMBL for now.

**Comment by the3ye** [comment]
Blacklisting apps helped. Thanks for the workaround!

By the way. Is there any way to rename sidebar items within icons10.plist or using some other plist file? Like changing "Documents to "Docs" without renaming the folder using alias?

**Comment by w0lfschild** [comment]
Well that functionality could be added in the future but it doesn't exist now.
