### ISSUE TITLE
VLC plural script does not work with macOS 10.12.6 (16G1114), when colorfulSidebar9 is installed.

### ISSUE THREAD

**Issue by Skogmann** [w0lfschild/colorfulSidebar_9#6]
On a MacBook Air (13-inch, Early 2015) 1,6 GHz Intel Core i5, the combination:
VLC plural script does not work with macOS 10.12.6 (16G1114), when colorfulSidebar9 is installed.

VLC 2.2.8

Script:
on run
    do shell script "open -n /Applications/VLC.app"
    tell application "VLC" to activate
end run

on open theFiles
    repeat with theFile in theFiles
        do shell script "open -na /Applications/VLC.app " & quote & (POSIX path of theFile) & quote
    end repeat
    tell application "VLC" to activate
end open

**Comment by w0lfschild** [comment]
I'm not sure what this is? Is VLC crashing?
