### ISSUE TITLE
persists after deinstallation?

### ISSUE THREAD

**Issue by danyisill** [w0lfschild/colorfulSidebar_9#8]
I removed the plugin, and after that i removed the SIMBL entirely but the icons are still colorful in the menu bar. The sidebar has old icons though
![2018-07-19 5 56 53](https://user-images.githubusercontent.com/23189912/42919057-db54f9c0-8b18-11e8-9345-ddb283dd1f72.png)

**Comment by w0lfschild** [comment]
Restart Finder?

**Comment by danyisill** [comment]
Yeah, I've restarted it, even after reboot it's still there

**Comment by danyisill** [comment]
Wait i think that's default on my os version sorry lmao
