### ISSUE TITLE
Not Working with Mojave 10.14

### ISSUE THREAD

**Issue by ghost** [w0lfschild/colorfulSidebar_9#9]
I have the latest versions of mySIMBL and ColorfulSideBar 1.5.0 installed. 
No changes to the side bar whatsoever in the dark or light modes.
cDock is working fine.

Any suggestions?

Thanks

**Comment by adityasrini** [comment]
I have this bug as well. Restarted Finder and it's still greyed out.

**Comment by adamwinn** [comment]
Any updates for a Mojave fix?

**Comment by dgentry** [comment]
Running macOS 10.14.5 (18F132) and the SIMBL and colorfulSidebar9 from today (June 1, 2019). Even after granting all the permissions that SIMBLAgent asks for and restarting Finder (and rebooting my Mac), still no colorful icons, although I thought I saw a blue gradient down the sidebar until I disabled colorfulSidebar9 in SIMBL but now I'm not seeing it.  I understand there is some other mechanism to get colorful icons now, but I actually wanted to use this to customize the icon for my Projects folder.  Getting a change in icons seems like the first step, but I'm getting nothing.

**Comment by adamwinn** [comment]
@dgentry
And what are the other ways to get colorful icons?

**Comment by semiopat** [comment]
Any news about a possible fix for Mojave ?

**Comment by adamwinn** [comment]
XtraFinder is what I used in the past for sidebar colors but then it stopped working after development stopped.  I just checked and development is active again and a version that support Mojave is out!  

https://www.trankynam.com/xtrafinder/

<img width="573" alt="sidebar_colors" src="https://user-images.githubusercontent.com/3028964/63071602-2d62a480-bedd-11e9-8845-6c70d586c931.png">

**Comment by w0lfschild** [comment]
Versions 1.6.0 and up should work on Mojave and Catalina
